name: Deployment actions

on:
  push:

jobs:
  run_ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Ruff
        run: ruff check .

      - name: Show Ruff Issues (if any)
        if: failure()
        run: echo "There are errors, check the logs"

  unit_testing:
    runs-on: ubuntu-latest
    env:
      OPEN_WEATHER_API_KEY: ${{ secrets.OPEN_WEATHER_API_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Cache pip dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

  export_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: totemic-client-447220-r1
          service_account_key: ${{ secrets.GCP_API_KEY }}

      - name: Authenticate with service account
        run: |
          echo '${{ secrets.GCP_API_KEY }}' | jq '.' > $HOME/gcloud-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcloud-key.json

      - name: Deploy get_warsaw_temperature to Google Cloud Functions
        run: |
          gcloud functions deploy get_warsaw_temperature \
          --allow-unauthenticated \
          --gen2 \
          --runtime python311 \
          --trigger-http \
          --entry-point get_warsaw_temperature \
          --region europe-central2 \
          --source . \
          --set-env-vars OPEN_WEATHER_API_KEY=${{ secrets.OPEN_WEATHER_API_KEY }} \
          --service-account=test-account@totemic-client-447220-r1.iam.gserviceaccount.com

      - name: Deploy hello_pubsub to Google Cloud Functions
        run: |
          gcloud functions deploy hello_pubsub \
          --allow-unauthenticated \
          --gen2 \
          --runtime python311 \
          --trigger-topic demo-topic \
          --entry-point hello_pubsub \
          --region europe-central2 \
          --source . \
          --set-env-vars OPEN_WEATHER_API_KEY=${{ secrets.OPEN_WEATHER_API_KEY }} \
          --service-account=test-account@totemic-client-447220-r1.iam.gserviceaccount.com
